/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.2/samples
 * This project uses @Incubating APIs which are subject to change.
 */

group = project.property("group") as String
version = project.property("version") as String

plugins {
    alias(libs.plugins.spotless)
    alias(libs.plugins.dependencycheck)
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

// https://github.com/diffplug/spotless/blob/main/plugin-gradle/README.md
spotless {
    // limit format enforcement to files changed by this branch
    ratchetFrom("origin/main")

    format("misc") {
        target(
            "*.gradle",
            ".gitattributes",
            ".gitignore",
        )
        trimTrailingWhitespace()
        leadingSpacesToTabs() // or leadingTabsToSpaces. Takes an integer argument if you don't like 4
        endWithNewline()
    }
    kotlinGradle {
        ktlint()
    }
    format("markdown") {
        target("**/*.md")
        prettier(
            mapOf(
                "prettier" to "3.6.2",
            ),
        ).npmInstallCache()
    }
    format("yaml") {
        target("**/*.y*ml")
        prettier(
            mapOf(
                "prettier" to "3.6.2",
            ),
        ).npmInstallCache()
    }
    format("xml") {
        target("**/*.xml")
        prettier(
            mapOf(
                "prettier" to "3.6.2",
                "@prettier/plugin-xml" to "3.4.2",
            ),
        ).config(
            mapOf(
                "plugins" to listOf("@prettier/plugin-xml"),
                "tabWidth" to 3,
                "printWidth" to 2048,
                "xmlSelfClosingSpace" to false,
            ),
        ).npmInstallCache()
    }
    format("toml") {
        target("**/*.toml")
        prettier(
            mapOf(
                "prettier" to "3.6.2",
                "prettier-plugin-toml" to "2.0.6",
            ),
        ).config(
            // plugin doesn't use taplo config file so replicating here :(
            mapOf(
                "plugins" to listOf("prettier-plugin-toml"),
                "alignEntries" to true,
                "alignComments" to true,
            ),
        ).npmInstallCache()
    }
}

// https://dependency-check.github.io/DependencyCheck/dependency-check-gradle/configuration-aggregate.html
dependencyCheck {
    nvd {
        apiKey = System.getenv("NVD_API_KEY") ?: project.findProperty("nvd.api.key") as String?
    }

    // Aggregate configuration
    scanConfigurations = listOf("runtimeClasspath")
    scanProjects =
        listOf(
            "services:patient-service",
        )
    outputDirectory = "build/reports/dependency-check"
    failBuildOnCVSS = 7.0f
}
